//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIN.Pages.Admin {
    
    
    public partial class RolesAndUsers {
        
        /// <summary>
        /// ctrl_RulesAndUsers1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Admin.ctrl_RulesAndUsers ctrl_RulesAndUsers1;
    }
}
