//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIN.Pages.User {
    
    
    public partial class Connections {
        
        /// <summary>
        /// Ctrl_ShowConnections1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_ShowConnections Ctrl_ShowConnections1;
        
        /// <summary>
        /// Ctrl_ViewSentRequests1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_ViewSentRequests Ctrl_ViewSentRequests1;
        
        /// <summary>
        /// Ctrl_SendRequest1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_SendRequest Ctrl_SendRequest1;
        
        /// <summary>
        /// Ctrl_ViewRequest1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_ViewRequest Ctrl_ViewRequest1;
    }
}
