//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIN.Pages.User {
    
    
    public partial class EditCertificate {
        
        /// <summary>
        /// ctrl_EditCerticicate1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.ctrl_EditCerticicate ctrl_EditCerticicate1;
    }
}
