//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIN.Pages.Users {
    
    
    public partial class MyProfile {
        
        /// <summary>
        /// Ctrl_MyProfilePic1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_MyProfilePic Ctrl_MyProfilePic1;
        
        /// <summary>
        /// Ctrl_viewUpdateSkill1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::LinkedIN.Controls.Users.Ctrl_viewUpdateSkill Ctrl_viewUpdateSkill1;
    }
}
