//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Skill {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skill() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Skill", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Skill.
        /// </summary>
        internal static string AddNewSkill {
            get {
                return ResourceManager.GetString("AddNewSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Skill.
        /// </summary>
        internal static string AddSkill {
            get {
                return ResourceManager.GetString("AddSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsements.
        /// </summary>
        internal static string Endorsements {
            get {
                return ResourceManager.GetString("Endorsements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorsers.
        /// </summary>
        internal static string Endorsers {
            get {
                return ResourceManager.GetString("Endorsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse/DeEndorse.
        /// </summary>
        internal static string Endorse_DeEndorse {
            get {
                return ResourceManager.GetString("Endorse_DeEndorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Endorsers.
        /// </summary>
        internal static string ShowEndorsers {
            get {
                return ResourceManager.GetString("ShowEndorsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level.
        /// </summary>
        internal static string SkillLevel {
            get {
                return ResourceManager.GetString("SkillLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Level .
        /// </summary>
        internal static string SkillLevelName {
            get {
                return ResourceManager.GetString("SkillLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        internal static string SkillName {
            get {
                return ResourceManager.GetString("SkillName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Name.
        /// </summary>
        internal static string SkillName1 {
            get {
                return ResourceManager.GetString("SkillName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
    }
}
